### ISSUE TITLE
Unable to set custom HttpClient

### ISSUE THREAD

**Issue by doppiak** [OpenUnirest/unirest-java#42]
It seems that custom HttpClient was overridden by default HttpClient.

**Comment by ryber** [comment]
Can you be more specific about what you are experiencing? These tests show setting and using a custom client and they are passing:

**Comment by ryber** [comment]
https://github.com/OpenUnirest/unirest-java/commit/ea74b3db922e8ea980c8051fdf19eabdef01337d

**Comment by fkleon** [comment]
I've experienced the same behaviour.

It seems that you need to call `Options.init()` *before* setting the custom HttpClient. Otherwise the defaults are initialised when `Options.warmUp()` is called internally, overwriting the custom HttpClient.

The tests are doing this in the `@Before` method here: https://github.com/OpenUnirest/unirest-java/blob/f23b6c8a6b569d8eec0a8f7deac6003f278900f7/src/test/java/BehaviorTests/BddTest.java#L27

**Comment by ryber** [comment]
*sigh* the whole options are a mess, which is why I'm totally redoing it in the v3 branch/ I've push in what I think should be a fix for this. It makes the client building more lazy, similar to v3. it's just way more annoying in the static context.

2.5.03 should be in maven central in about 10-20 minutes
