### ISSUE TITLE
How to get Response Body on server error

### ISSUE THREAD

**Issue by philippendrulat** [OpenUnirest/unirest-java#49]
My Problem:
* I want to get an object from a server. The type is MyType.class.
* The server throws an exception. It sends a message of the exception in the Http Body.
* The body is not of type MyType.class 

Now, I want to know the body. In Version 2, this was possible by using HttpResponse.getRawBody(). Unfortunately, now the response body is null and the raw body is an empty InputStream. Since the object mapper tries to map it to MyType.class, an exception gets thrown and the exception gets saved as HttpResponse.parsingError. 

How do I access the message of the server? I could see the message if I override the ObjectMapper, catch the exception and extend the exception by the original body, but I don't think this is the intended way.

**Comment by ryber** [comment]
Sorry, my hope was that the exception would have enough of the body for you to get that from the exception. It did with Jackson in my tests at least. I've been working on deprecating the rawBody method because it's rather problematic. It's kind of a lie, it's only ever a reproduction of the raw response and not the real original, and there are better ways to deal with the issue.

Speaking of which, I just released a new version (3.1.02) that has what I think is a  better solution. the parsingException is now a ```UnicodeParsingException``` which contains both the original Exception as ```cause``` and the original body which you can get as a string from ```ex.getOriginalBody()```

This works with body ```asObject``` and ```asJson```

I'd appreciate any feedback. It will take 10-20 minutes before it makes it through the labyrinth of Maven Central.

**Comment by philippendrulat** [comment]
Are you sure you released the version? Or is maven just slower than expected? There is no version 3.1.02 for me at https://mvnrepository.com/artifact/io.github.openunirest/open-unirest-java

**Comment by ryber** [comment]
The UI of maven central takes up to a day (sometimes more) to update. If you look in the raw directiory it's there: https://repo.maven.apache.org/maven2/io/github/openunirest/open-unirest-java/

**Comment by philippendrulat** [comment]
You are right. 
The solution works!
I'd just wish for a hint in the javadoc for all the getBody methods, where the body is stored on parsing error.

Thank you for your work!

**Comment by ryber** [comment]
Thanks, yea, Ill get the doc and the examples updated. The problem with the body is that it's T and String is not T, We also don't want to just store the body twice if we don't need to. If only Java had a ```either``` like Scala it might be easier (people have done it but it's just never as nice as the Scala version ... (I'm not actually a huge Scala fan but this part is nice))
