### ISSUE TITLE
SSL - Server Name Indication problem

### ISSUE THREAD

**Issue by Flayovec** [OpenUnirest/unirest-java#52]
Hello, I have problem with accesing [this](https://www.ceskereality.cz) page, problem is with SSL certificate, exception message: `javax.net.ssl.SSLException: hostname in certificate didn't match` If I open this page in browser (Google Chrome on Windows 10) there isn't any problem. Thanks for any help

**Comment by ryber** [comment]
Unirest itself doesn't do SSL negotiation. That is actually handled by Java itself, in any case the cert on that URL looks fine, although fairly behind on security standards, you can test it on any number of online tools like this one: https://www.ssllabs.com/ssltest/analyze.html?d=www.ceskereality.cz


The reason you may be getting an error is due to a something injecting itself in your network, it could be malware or improperly configured proxies etc.

**Comment by Flayovec** [comment]
When the request is made synchronous it works, but if I made it async it throws exception. So problem must be somewhere in AsyncClient, isn't it ?

**Comment by ryber** [comment]
It works fine for me with async as well. I get a 200:

```
 Unirest.get("https://www.ceskereality.cz")
                .asStringAsync()
                .get()
                .ifSuccess(r -> {
                    System.out.println("Status = " + r.getStatus());
                    System.out.println("StatusT = " + r.getStatusText());
                });
```

**Comment by Flayovec** [comment]
Problem is really simple 😂 When I was upgrading from old Unirest to this fork, I didn't remove maven dependencies of old Unirest... Now it works, thanks !
